### ISSUE TITLE
Automagically create Points (and maybe Angles) when functions are passed Tuples

### ISSUE THREAD

**Issue by rvodden** [rvodden/pysketcher#27]
I think that this kind of code is kinda ugly:

```
line = Line(Point(1,2), Point(1,5))
```

It would be much cleaner if the constructor accepted a `tuple`:
```
line = Line((1,2), (1,5))
```

However, that would make for some messy code in the constructor. I propose instead that we spin up a decorator called `autopoint` (open to other suggestions) which will wrap the constructor like so:

```
class Line:

    @autopoint
    def __init__(self, a: Point, b: Point) -> None:
        # initialize line
```

This wrapper would replace all parameters of type `Point` with type `Union[Point,Type[float,float]]` and detect if a tuple is passed in, doing the point construction on the fly if necessary. This means that the user gets the best experience, as they can just use `(1,2)` and the developer gets the best experience as they don't have to mess around constructing points.

A very similar thing could happen for parameters of type `Angle`.

**Comment by ReblochonMasque** [comment]
It probably feels like a good idea at first: that is great, we can suddenly transform any tuple of numbers indiscriminately into a Point or a Vector, the need to type the type of the object has vanished, and we've saved 4 seconds... We can also make lists of tuples that feed a function from a loop without bothering to create the proper objects... Life is good, what could possibly go wrong?

Then, after it is impossible to yank out this convenience, because everyone is using it (and why not, it is offered, so it is good, no?), we find that those 4 seconds saved have robbed us of understanding what we are doing... Are we creating a point, or a vector? Can I add these 2 objects together? Does it make sense to multiply them by this matrix?
But by then, it is too late, we have to live in a world where any tuple can represent anything. We have lost control of our thoughts, forgotten the understanding of our mechanical system, and gotten ourselves irreparably confused!

In brief, I think this is a terrible idea!
I am a proponent of strongly type to distinguish every different object that needs to be identified.
